#!/bin/bash

_NODEJS_HOME="${_NODEJS_HOME:-$PROGSATIVOS_DIR/nodejs/current}"
export PATH=$_NODEJS_HOME/bin:$PATH

export CAPACITOR_ANDROID_STUDIO_PATH="${CAPACITOR_ANDROID_STUDIO_PATH:-${ANDROID_STUDIO_HOME:+$ANDROID_STUDIO_HOME/bin/studio.sh}}"
